rem Generated by MSBuild Small.proj.
rem Date:   2022-02-23 18:42:44.7615487
rem User:   cc
rem System: MACHINE-NR5C9PV\MACHINE-NR5C9PV

set _BOOTD_TFTP_DIR=C:\Users\cc\source\repos\Singularity-OS\base.obj\Distros\Small.Debug.ApicMP.MarkSweep.Min.Concurrent
set _BOOT_ISO=C:\Users\cc\source\repos\Singularity-OS\base.obj\Distros\Small.Debug.ApicMP.MarkSweep.Min.Concurrent.iso
set _NT_DEBUGGER_EXTENSION_PATH=C:\Users\cc\source\repos\Singularity-OS\base\build
set _NT_SOURCE_PATH=srv*;C:\Users\cc\source\repos\Singularity-OS\base;C:\Users\cc\source\repos\Singularity-OS\base\Applications;C:\Users\cc\source\repos\Singularity-OS\base\Boot;C:\Users\cc\source\repos\Singularity-OS\base\drivers;C:\Users\cc\source\repos\Singularity-OS\base\interfaces;C:\Users\cc\source\repos\Singularity-OS\base\kernel;C:\Users\cc\source\repos\Singularity-OS\base\Libraries;C:\Users\cc\source\repos\Singularity-OS\base\Services
set _NT_SYMBOL_PATH=C:\Users\cc\source\repos\Singularity-OS\base.obj\AppNativeObj\Debug.x86.MarkSweep;C:\Users\cc\source\repos\Singularity-OS\base.obj\Kernel\Debug.x86.ApicMP.Min.Concurrent.native;
